linters:
  enable:
    - bodyclose     # Checks whether HTTP response body is properly closed
    - dogsled       # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - dupl          # Tool for code clone detection
    - errcheck      # Checks for unchecked errors in go programs
    - errorlint     # Finds code that will cause problems with the error wrapping scheme
    - forbidigo     # Forbids identifiers (useful for restricting usage of some functions)
    - goconst       # Finds repeated strings that could be replaced by a constant
    - gocritic      # Provides extensive code analysis with many diagnostics
    - gocyclo       # Checks function complexity to find overly complex functions
    - godot         # Checks if comments end in a period to ensure consistency
    - gofmt         # Formats Go source code according to the Go standard
    - goimports     # Updates Go imports and formats code like gofmt
    - gosec         # Inspects source code for security problems by scanning the Go AST
    - gosimple      # Specializes in simplifying code
    - govet         # Reports suspicious constructs, such as Printf calls with wrong arguments
    - ineffassign   # Detects when assignments to existing variables are not used
    - makezero      # Finds slice declarations with non-zero initial length
    - misspell      # Finds commonly misspelled English words in comments
    - nakedret      # Finds naked returns in functions greater than a specified size
    - nilerr        # Finds redundant nil checks on errors
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - predeclared   # Finds code that shadows Go's predeclared identifiers
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - staticcheck   # State of the art linter for Go, providing advanced checks
    - stylecheck    # Replacement for golint with additional checks and more strict
    - thelper       # Detects Test helper functions that don't start with t.Helper()
    - tparallel     # Detects inappropriate usage of t.Parallel() method in tests
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - whitespace    # Tool for detecting and fixing whitespace issues
    - wsl           # Enforces consistent whitespace style

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  goconst:
    min-len: 3
