linters:
  enable-all: false
  disable:
    - depguard      # Enable if need to vet dependencies
    - exportloopref
    - mnd
    - paralleltest  # Enable for t.Parallel checks.
    - varnamelen
    - wsl
    - wrapcheck
    # planned to fix:
    - err113
    - funlen
    - lll
    - testifylint
    - testpackage
    - cyclop

  enable:
    - asasalint     # Checks for pass []any as any in variadic position
    - bodyclose     # Checks whether HTTP response body is properly closed
    - containedctx  # Detects struct contained context.Context field
    - dogsled       # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - dupl          # Tool for code clone detection
    - errcheck      # Checks for unchecked errors in go programs
    - errorlint     # Finds code that will cause problems with the error wrapping scheme
    - exhaustive    # Checks exhaustiveness of enum switch statements
    - exhaustruct
    - forbidigo     # Forbids identifiers (useful for restricting usage of some functions)
    - gci
    - goconst       # Finds repeated strings that could be replaced by a constant
    - gocritic      # Provides extensive code analysis with many diagnostics
    - gocyclo       # Checks function complexity to find overly complex functions
    - godot         # Checks if comments end in a period to ensure consistency
    - gofmt         # Formats Go source code according to the Go standard
    - gofumpt       
    - gosec         # Inspects source code for security problems by scanning the Go AST
    - goimports     # Tool for automatically importing packages
    - gosimple      # Specializes in simplifying code
    - govet         # Reports suspicious constructs, such as Printf calls with wrong arguments
    - ineffassign   # Detects when assignments to existing variables are not used
    - makezero      # Finds slice declarations with non-zero initial length
    - misspell      # Finds commonly misspelled English words in comments
    - nakedret      # Finds naked returns in functions greater than a specified size
    - inamedparam
    - intrange
    - ireturn
    - nilerr        # Finds redundant nil checks on errors
    - nilnil        # Checks that there is no simultaneous return of nil error and nil value
    - nlreturn
    - noctx         # Finds sending HTTP requests without context.Context
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - perfsprint
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - predeclared   # Finds code that shadows Go's predeclared identifiers
    - reassign      # Checks that package variables are not reassigned
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - staticcheck   # State of the art linter for Go, providing advanced checks
    - stylecheck    # Replaces golint
    - tenv          # Detects using os.Setenv instead of t.Setenv in tests
    - thelper       # Detects Test helper functions that don't start with t.Helper()
    - tparallel     # Detects inappropriate usage of t.Parallel() method in tests
    - typecheck     # Checks that types are correct
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - unused        # Finds unused packages, functions, variables, and constants
    - wastedassign  # Finds wasted assignment statements
    - whitespace    # Tool for detecting and fixing whitespace issues

run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  goconst:
    min-len: 3

