version: '3'

tasks:
  default:
    cmds:
      - task: lint
      - task: test

  lint:
    desc: Runs golangci-lint
    aliases: [l]
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run

  lint:fix:
    desc: Runs golangci-lint and fixes any issues
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run --fix

  packages:
    desc: Shows list of packages
    cmds:
      - go list ./...

  run:app:
    desc: Runs application
    cmds:
      - go run ./cmd/connect/main.go

  test:
    desc: Runs test suite
    cmds:
      - go test ./...

  test:cover:
    desc: Runs test suite with coverage
    cmds:
      - go test ./... --cover --count=1

  tidy:
    desc: Runs go mod tidy
    cmds:
      - go mod tidy