# SPDX-FileCopyrightText: © 2025 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT

---
version: '3'

tasks:
  default:
    cmds:
      - task --list --sort=alphanumeric

  check:all:
    desc: Lint and test
    aliases: [all]
    deps: [lint, test]

  fmt:
    desc: Runs go fmt
    cmds:
      - go fmt ./...

  git:discard:
    desc: Discards unstaged changes
    aliases: [discard]
    cmds:
      - git checkout -- .

  lint:
    desc: Runs golangci-lint
    aliases: [l]
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run

  lint:new:
    desc: Runs golangci-lint
    aliases: [ln]
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run --new

  lint:fix:
    desc: Runs golangci-lint and fixes any issues
    aliases: [lf]
    sources:
      - './**/*.go'
      - .golangci.yml
    cmds:
      - golangci-lint run --fix

  packages:
    desc: Shows list of packages
    aliases: [p]
    cmds:
      - go list ./...

  run:app:
    desc: Runs application
    aliases: [r]
    cmds:
      - go run ./cmd/connect/main.go

  test:
    desc: Runs test suite
    aliases: [t]
    cmds:
      - go test ./...

  test:cover:
    desc: Runs test suite with coverage
    aliases: [tc]
    cmds:
      - go test ./... --cover --count=1

  tidy:
    desc: Runs go mod tidy
    cmds:
      - go mod tidy
